source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'active_model_serializers', '~> 0.9.3'
gem 'rack-cors', :require => 'rack/cors'
gem 'kaminari', '~> 0.16.3'
gem 'ancestry', '~> 2.1.0'
gem 'angular_rails_csrf', '~> 1.0.4'
gem 'devise_token_auth', '~> 0.1.36'
gem 'omniauth', '~> 1.2.2'


# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
group :development do
  gem 'thin', '~> 1.6.3'
  gem 'rails-erd', '~> 1.4.0'
  gem 'mailcatcher', '~> 0.2.4'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'pry', '~> 0.10.1'
  gem 'pry-rails', '~> 0.3.4'
end

